### ISSUE TITLE
Term start countdown is incorrect.

### ISSUE THREAD

**Issue by SCKelemen** [wearehx/voting#28] opened 2016-03-21 23:01 UTC
(image removed by @iangcarroll)

**Comment by iangcarroll** [comment] 2016-03-21 23:02
Nothing is incorrect; oddly phrased, I guess. Will fix eventually.

**Comment by iangcarroll** [comment] 2016-03-21 23:03
This is a duplicate of #13 regardless. You should also delete that image, given it has your UUID in it.

**Closed as completed by iangcarroll** 2016-03-21 23:03 UTC
